version: "3"
services:
  server:
    image: rohitkolapkar/bookmyappointment
    ports:
      - "8080:8080"
    environment:
    #observe mysqldb:3306 <-- mysqldb is service name
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bookmyappointment?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookmyappointment
      - MYSQL_USER=rohit
      - MYSQL_PASSWORD=rohit

networks:
  springmysql-net: